### ISSUE TITLE
Async mode logging unnecessary  messages

### ISSUE THREAD

**Issue by alfetahe** [Azolo/websockex#108]
When starting the connection using the `async: true` option in the `start_link/4` function the library starts logging some messages.
For example:
`{#Reference<0.2707508044.11272194.150465>, :ok}
{:DOWN, #Reference<0.2707508044.11272194.150465>, :process, #PID<0.1226.0>,
 :normal}`
This is no big problem until I run tests that heavily use websockex connections underneath. I get so many of those messages that I'm unable to see the actual test results.
This probably happens for the following reasons:
1. Websockex start init process and starts the real ws process asynchronously.
2. Once the real connection is up the init process is dropped and probably causing the problem.
3. The messages get printed to the screen.

Is there anything I can do to supress those messages?

**Comment by Azolo** [comment]
Can you tell me what version of Erlang and Elixir you're using?

**Comment by alfetahe** [comment]
Elixir 1.12.2 and Erlang/OTP 24.

**Comment by Azolo** [comment]
Sorry, I haven't had time to look into this yet.

**Comment by alfetahe** [comment]
The problem was with my code. Basically I was logging out these messages from the genserver.
