### ISSUE TITLE
`handle_connect/2` first connection

### ISSUE THREAD

**Issue by Zat42** [Azolo/websockex#109]
Is there a way to know in callback [handle_connect/2](https://hexdocs.pm/websockex/WebSockex.html#c:handle_connect/2) if this is a first connection or a reconnection?

My problem there is that I initialize something at first connection and I need to do it only once. I couldn't find anything helfpul in [Websocket.Conn](https://hexdocs.pm/websockex/WebSockex.Conn.html#t:t/0) to help me on this.

Also, I don't understand why there is no `init/1` [callback](https://hexdocs.pm/elixir/1.12/GenServer.html#c:init/1) like GenSever, is there a specific reason for this?

**Comment by Azolo** [comment]
I think at one point I had something like an `init/1` in there, but I felt that it made the API confusing.

In your case, I would suggest that you have something in your state that signifies that you haven't been through your first connect. If you need to then invoke the other `handle_connect/2` with the state updated.

```elixir
def handle_connect(_, %{connected: true} = state) do
  ...
end

def handle_connect(conn, state) do
  ...
  handle_connect(conn, Map.put(state, :connected, true)) # If you want to run the other `handle_connect/2` instead of return.
end
```
