### ISSUE TITLE
Undetected disconnect after successfull connection.

### ISSUE THREAD

**Issue by h4cc** [Azolo/websockex#11]
Thanks for this great library!

I wanted to test disconnection behaviour and tried this:

1. Connect successfully with websocket and let the connection idle.
2. Disconnect the WIFI from my computer, which is the only internet connection it has.
3. Wait for `handle_disconnect` to be called, which is not the case.
4. Profit!

Did i do something wrong? Is there a other way to test this?

I also tried to use `active: true` mode, and fiddling with `wait_for_response` which did not help detecting the disconnect.

**Comment by h4cc** [comment]
I tried using `send_timeout`, which should be set to something like 1000 imho, otherwise :infinity might be the setting.

The docs also state, that after a failed gen_tcp.send it would be best to close the socket and start over (bottom of page):
http://erlang.org/doc/man/gen_tcp.html#type-option

**Comment by Azolo** [comment]
In the case of a connection failure like that you would have to send data on the TCP socket to figure out that there's a dead connection. Just terminating the WAN connection wouldn't do anything. Your second comment makes it sound like you tried sending a frame along the line, but I just want to make sure before I jumped down into this rabbit hole.

So in essence you did nothing wrong, but there's also a good chance that neither did the library. If you sent something on the line and nothing happened, then I would need to look at how Erlang handles the TCP `ACK`s and such then figure out if it's a good idea for me to implement checking for dead connections that way.

In terms of how the connections stays "open" and "connected" are usually done through a heartbeat contract between the two peers. The WebSocket spec has a built-in heartbeat mechanism. However, there are many ways to handle those heartbeats, plus server specific options. Also, the entire thing is optional. So I just built the underlying WebSocket tools to handle the server's heartbeat contract into the library as well as a smart `Pong` response to a server's `Ping` frame (incase that was the mechanism being used).

**Comment by Azolo** [comment]
I did some testing, and the TCP socket does in fact close when trying to send data over a disconnected connection.

If there's something else that I'm missing, or you still don't feel like it is functioning properly please feel free to reopen this ticket with more information.

**Comment by h4cc** [comment]
Okay, then we need to go down the rabbit hole here.

Using `inet.getopts` i got the effective socket options i tried:
```
{:ok,   
 [mode: :binary, active: true, buffer: 1460, delay_send: false, deliver: :term,
  dontroute: false, exit_on_close: true, header: 0, high_msgq_watermark: 8192,
  low_msgq_watermark: 4096, high_watermark: 8192, low_watermark: 4096,
  keepalive: true, linger: {false, 0}, nodelay: true, packet: 0, packet_size: 0,
  priority: 0, recbuf: 372480, reuseaddr: false, send_timeout: 1,
  send_timeout_close: true, show_econnreset: true, sndbuf: 87040, tos: 0]}
```
I tried some of them i thought would make a difference, but had no effect for the socket:
* `send_timeout: 1`
* `send_timeout_close: true`
* `show_econnreset: true`
* `keepalive: true`

When intercepting the `receive` in `websocket_loop` i never saw any `{:tcp_close, ...}` when network went down. When my network was up again the TCP connection went transparently up again without calling `handle_connect`.

My machine is a Xubuntu 17.04 with Erlang 19.3-1 and Elixir 1.4.4. What do you use?

**Comment by Azolo** [comment]
> When intercepting the receive in `websocket_loop` i never saw any `{:tcp_close, ...}` when network went down. When my network was up again the TCP connection went transparently up again without calling `handle_connect`.

That is correct, that's the intended behavior because that's how TCP sockets work.

When there is no data on the line, the only think that is happening is that we are listening at both ends. If data is sent that can't be delivered, then it registers as an error and the socket is closed. Which is why the [`ping` frame][1] exists in the specification.

After disconnecting try sending a frame across the WebSocket. That's the only way to detect a lost TCP connection after a connection failure.

[1]: https://tools.ietf.org/html/rfc6455#section-5.5.2
