### ISSUE TITLE
Recognizing disconnect?

### ISSUE THREAD

**Issue by steveklebanoff** [Azolo/websockex#27]
Hi there,

I've been using WebSockex for a project, but I've been having trouble having the socket know when we've lost connection.

For example, when I am connected to a web socket, and disconnect from wifi, `handle_disconnect` does not trigger.  When I reconnect to wifi, it keeps receiving messages.

Is there anyway for the web socket to recognize the loss of connection in this case?

Thanks for the help!

**Comment by Azolo** [comment]
No, WebSocket is an just underlying TCP socket.

It will only recognize a disconnect when you try to send an outgoing message, otherwise it is just open and listening.

**Comment by steveklebanoff** [comment]
Got it, makes sense.  Thanks for following up.

In my case, I'm listening to a websocket that should be sending messages every second or so.  I needed a way to raise an error if a message hasn't been received after a certain amount of time.  I ended up switching to use https://github.com/meh/elixir-socket and continually calling `Socket.Web.recv!([timeout: my_timeout])`. 

Is there a way to do something similiar using websockex?  If so, that'd be awesome, as I prefer the simplicity of websockex over having to use elixir-socket

**Comment by Azolo** [comment]
So there is a way to accomplish what you're wanting to. But it requires you to think about the problem a little bit differently.

```elixir
defmodule SocketWithTimeout do
  use WebSockex

  # `start_link` and such oh and `state` is a map here

  def handle_connect(_conn, state) do
    timer_ref = Process.send_after(self(), :timeout, 120000)
    {:ok, Map.put(state, :timer_ref, timer_ref)}
  end

  def handle_frame(frame, %{timer_ref: timer_ref} = state) do
    cancel_timer(timer_ref)
    ... Logic Stuffs ...
    new_timer_ref = Process.send_after(self(), :timeout, 120000)
    {:ok, %{state | timer_ref: new_timer_ref}}
  end

  handle_info(:timeout, state) do
    {:close, state}
  end

  # Flush the mailbox if we failed to cancel the timer
  defp canel_timer(ref) do
    case Process.cancel_timer(ref) do
    i when is_int(i) -> :ok
    false ->
      receive do
        :timeout -> :ok
      after
        0 -> :ok
      end
  end
end
```

**Comment by steveklebanoff** [comment]
I think given my use case, using elixir-socket to call `recv!` with a timeout value is a bit simpler to reason about (see https://github.com/steveklebanoff/arbie/blob/master/lib/arbie/clients/json_web_socket.ex) than keeping track of these timers. That being said, thanks for taking the time to write this up, I appreciate it

**Comment by Azolo** [comment]
Sure thing! Just remember that during that `recv!` your `GenServer` will be blocking and won't handle other messages.
