### ISSUE TITLE
Provide a better error when :websockex application isn't started

### ISSUE THREAD

**Issue by wpcarro** [Azolo/websockex#31]
You include in one of your examples the line:

```elixir
WebSockex.start_link("wss://echo.websocket.org/?encoding=text", __MODULE__, :state)
```

When I run the same line of code, I get `WebSockex.URLError{..}`. I believe this code is because of the `parse_uri/1` implementation:

```elixir
    case URI.parse(url) do
      # This is confusing to look at. But it's just a match with multiple guards
      %URI{host: host, port: port, scheme: protocol}
      when is_nil(host)
      when is_nil(port)
      when not protocol in ["ws", "wss"] ->
        {:error, %WebSockex.URLError{url: url}}
      %URI{} = uri ->
        {:ok, uri}
    end
```

The result of calling `URI.parse("wss://echo.websocket.org/?encoding=text")` is going to return `%URI{..., port: nil, ...}`. Is there a reason you're asserting on the port being present? Or rather, is there a reason that the example code is compiling for you and not for me? Other URLs that I've tried have returned `WebSockex.URLError`s as well, which is confusing me.

**Comment by Azolo** [comment]
You need to start the WebSockex application, that's when the [`ws` and `wss` protocols get registered][1].

In your `mix.exs` file do:

```
def application do
  [applications: [:websockex]]
end
```

or start it manually using:

    Application.ensure_all_started(:websockex)

[1]: https://github.com/Azolo/websockex/blob/master/lib/websockex/application.ex

**Comment by wpcarro** [comment]
Thanks for the response, @Azolo. Are we sure that `URLError{..}` is the type of error that should be used in these circumstances? It was definitely misleading in my case Or perhaps there is additional information that can be conveyed to the user in cases where the port is `nil` and the application hasn't started.

**Comment by Azolo** [comment]
Good point. Alright I'll try to think of something that conveys more information about the error.
