### ISSUE TITLE
Allow Connecting with a Client Certificate

### ISSUE THREAD

**Issue by ulutomaz** [Azolo/websockex#33]
Hi,

I need to connect with Elixir to a remote Websocket using the client certificate. Would it be possible to put something about this into the documentation. How and where do you specify where is the TLS certificate that you would use at connection establishment?

I looked but can't really find anything on this in the docs.

Many thanks,

Tomaz

**Comment by Azolo** [comment]
WebSockex isn't actually able to do that... yet.

I've been wanting to look at reworking the `:ssl` module options.

If you want to look at patching for yourself in the interim, take a look at where the [ssl options are current being set][1]. The options for the [Erlang `:ssl` module are here][2]. But beware, the `:ssl` module in Erlang is not very forgiving.

If you need to debug, then it would probably be easier to get a regular `:ssl` connection using `:ssl.connect/4` then adding those options until I get something else more configurable built for the `:ssl` module.

[1]: https://github.com/Azolo/websockex/blob/master/lib/websockex/conn.ex#L254-L270
[2]: http://erlang.org/doc/man/ssl.html#type-ssloption

**Comment by steffkes** [comment]
@Azolo i did need handling for client certificates as well and just gave it a first try, the patch is rather small (about ten lines) and would allow passing `ssl` options to the `WebSockex.Conn` module - so it's up to the client to define the needed configuration. that's similar to [what HTTPoison does](https://github.com/edgurgel/httpoison/pull/252/files#diff-04c6e90faac2675aa89e2176d2eec7d8)

Would you be open to a PR for this? do you have anything else in mind - or probably already working elsewhere?

**Comment by steffkes** [comment]
what i hand in mind - because you already mentioned that ssl options are hard to get right - is that i'd pass that responsibility to the client (=user). define a basic set of options that are normally needed for working web sockets + the ability to pass in everything that's needed in addition to that. that way we keep the library small and focused but still go for flexibility

**Comment by steffkes** [comment]
since #61 is merged, i'd say we can close this issue @Azolo

**Comment by Azolo** [comment]
@steffkes Indeed
