### ISSUE TITLE
Use GenServer

### ISSUE THREAD

**Issue by pikeas** [Azolo/websockex#36]
You mentioned your plan to switch to a GenServer on the Elixir Forum thread. Adding a tracking issue for it. :)

**Comment by Azolo** [comment]
I actually did in #17. 😸 

Basically, I felt like being able to use `:sys` debugging tools to add the connection cycle was totally worth re-implementing the special process stuff.

**Comment by pikeas** [comment]
Nice! In that case, consider adding a note to the README explaining why you DIDN'T use a GenServer?
