### ISSUE TITLE
Connection closed unexpectedly

### ISSUE THREAD

**Issue by 1player** [Azolo/websockex#38]
I'm trying to connect to the GDAX Websocket API, whose sandbox URL is "wss://ws-feed-public.sandbox.gdax.com"

Calling WebSockex.start_link with that URL terminates immediately with `{:error, %WebSockex.ConnError{original: :closed}}`

Connecting to the echo server at "wss://echo.websocket.org" gives the same error, while "wss://echo.websocket.org/?encoding=text" works just fine.

What's more strange, is that if I use the GDAX production URL at "wss://ws-feed.gdax.com", the connection terminates immediately with `{:error, %WebSockex.RequestError{code: 400, message: "Bad Request"}}`

This does not happen with websocket_client (https://hex.pm/packages/websocket_client/1.3.0), which works perfectly.

What's going on here?

**Comment by Azolo** [comment]
That is a good question.

If I were to guess something differs in the request that is made.

I tried to make the request to spec, but I will look at the differences and see if I can figure it out.

**Comment by uzarubin** [comment]
I'm getting the same thing as @1player when trying to connect to GDAX

**Comment by Azolo** [comment]
@uzarubin Interesting. I'm using `URI` to parse the `url`. I guess I should make sure that it has the path of `/` if the url binary doesn't include it.

Thanks for the info!
