### ISSUE TITLE
Disable auto ping

### ISSUE THREAD

**Issue by anonrig** [Azolo/websockex#55]
Is there a way to disable auto ping by websockex?

**Comment by Azolo** [comment]
WebSockex doesn't auto ping, it does auto pong though. The default implementation of [the `handle_ping/2` callback][1] responds with a `pong`. You can override that behavior by declaring `handle_ping/2` yourself.

[1]: https://hexdocs.pm/websockex/WebSockex.html#c:handle_ping/2
