### ISSUE TITLE
Publish new version of hex package

### ISSUE THREAD

**Issue by rupurt** [Azolo/websockex#65]
Hi @Azolo,

When you get the chance could you please tag and publish a new version to hex?

There have been several changes/bug fixes since `0.4.1` earlier this year (Jan 22 2018). Packages that depend on `websockex` can't publish a new release against these changes using a reference to a github repo.

🍻

**Comment by Azolo** [comment]
Can it wait until I get back from holiday/vacation next week?

**Comment by rupurt** [comment]
Of course 😄 

Thanks for the quick response and enjoy the vacation!!

**Comment by Azolo** [comment]
Ok, I'll get one released in the next few days.

**Comment by rupurt** [comment]
Awesome. Cheers @Azolo

**Comment by Azolo** [comment]
Done, sorry it took so long.

https://github.com/Azolo/websockex/releases/tag/v0.4.2
https://hex.pm/packages/websockex/0.4.2

I'll do the other release stuff tomorrow.

**Comment by rupurt** [comment]
@Azolo cheers mate! 🍻
