### ISSUE TITLE
send params to websocket server

### ISSUE THREAD

**Issue by floodico** [Azolo/websockex#68]
Hello! I need to send some params to websocket server to check them during the connection... 
how can i do it?

**Comment by floodico** [comment]
that's my connection log on server: 
<img width="334" alt="screen shot 2018-12-26 at 11 41 25" src="https://user-images.githubusercontent.com/12949777/50441453-6ecd2200-0903-11e9-9ec7-896712ddb33a.png"> 
as can you see my parameters are empty. Can i pass some parameters there?

**Comment by floodico** [comment]
@Azolo yes, this really works. thank you! 
But what if I have a large map of parameters? Is this the only way to send them to the server?

**Comment by Azolo** [comment]
@floodico Yes

**Comment by Azolo** [comment]
@floodico I think I possibly misinterpreted your question the first time.

You can manually build a `WebSockex.Conn` struct that may be easier to manipulate.
