### ISSUE TITLE
Initial message from server is not received

### ISSUE THREAD

**Issue by dealloc** [Azolo/websockex#84]
I'm noticing that `handle_frame` is not called when the server sends a message immediately after connecting.
The following code:
```elixir
defmodule Wumpex.Discord.WebsocketClient do
  use WebSockex

  @socket_url "wss://gateway.discord.gg/?v=6&encoding=json"

  def start_link(opts \\ []) do
    WebSockex.start_link(@socket_url, __MODULE__, :no_state, opts)
  end

  @impl true
  def handle_frame(frame, state) do
    IO.puts "Received Message - Type: #{inspect frame}"

    {:ok, state}
  end
end
```
According to [the Discord spec](https://discordapp.com/developers/docs/topics/gateway#connecting-to-the-gateway), I should immediately receive a frame for the heartbeat.
**SOMETIMES** this actually occurs, and `handle_frame` is called, however this seems to happen occasionally and more often not than it does.

What I'm actually getting is more like this:
![Screenshot from 2020-05-01 22-53-07](https://user-images.githubusercontent.com/2164354/80840879-8fe00a00-8bfe-11ea-904c-2f1a71607233.png)

I'm running Elixir 1.10.1 with Erlang/OTP 22

**Comment by Azolo** [comment]
So, this is something that I actually remember fixing in the early stages.

https://github.com/Azolo/websockex/blob/ce7064e1d6e8dfb1bba1bb8d3e75b71b88aabc1e/test/websockex_test.exs#L471-L492

I haven't had the time to work on this recently, but there may be some TLS breaking changes that came with the new OTP versions.

I think maybe?

Can you clone the repo and run the rests for me real quick?

**Comment by dealloc** [comment]
I seem to get about 9 failing tests.

What stands out to me is failing test 8, "handles a SSL message send right after connecting"
I'm willing to work on a PR, if you can give me any pointers as to where I could start debugging this?

```
..

  1) test set_active works on wss connections (WebSockex.ConnTest)
     test/websockex/conn_test.exs:216
     ** (MatchError) no match of right hand side value: {:error, %WebSockex.ConnError{original: {:tls_alert, {:insufficient_security, 'TLS client: In state hello received SERVER ALERT: Fatal - Insufficient Security\n '}}}}
     code: {:ok, conn} = WebSockex.Conn.open_socket(conn)
     stacktrace:
       test/websockex/conn_test.exs:221: (test)

     The following output was logged:
     
     16:53:00.590 [info]  TLS :server: In state :hello at ssl_handshake.erl:1423 generated SERVER ALERT: Fatal - Insufficient Security
      - :no_suitable_signature_algorithm
     
     16:53:00.590 [info]  TLS :client: In state :hello received SERVER ALERT: Fatal - Insufficient Security
      
     


  2) test secure connection open_socket with insecure flag (WebSockex.ConnTest)
     test/websockex/conn_test.exs:163
     ** (MatchError) no match of right hand side value: {:error, %WebSockex.ConnError{original: {:tls_alert, {:insufficient_security, 'TLS client: In state hello received SERVER ALERT: Fatal - Insufficient Security\n '}}}}
     stacktrace:
       test/websockex/conn_test.exs:146: WebSockex.ConnTest.__ex_unit_setup_1/1
       test/websockex/conn_test.exs:1: WebSockex.ConnTest.__ex_unit__/2

     The following output was logged:
     
     16:53:00.602 [info]  TLS :server: In state :hello at ssl_handshake.erl:1423 generated SERVER ALERT: Fatal - Insufficient Security
      - :no_suitable_signature_algorithm
     
     16:53:00.613 [info]  TLS :client: In state :hello received SERVER ALERT: Fatal - Insufficient Security
      
     
.

  3) test secure connection open_socket with custom ssl options (WebSockex.ConnTest)
     test/websockex/conn_test.exs:179
     ** (MatchError) no match of right hand side value: {:error, %WebSockex.ConnError{original: {:tls_alert, {:insufficient_security, 'TLS client: In state hello received SERVER ALERT: Fatal - Insufficient Security\n '}}}}
     stacktrace:
       test/websockex/conn_test.exs:146: WebSockex.ConnTest.__ex_unit_setup_1/1
       test/websockex/conn_test.exs:1: WebSockex.ConnTest.__ex_unit__/2

     The following output was logged:
     
     16:53:00.629 [info]  TLS :server: In state :hello at ssl_handshake.erl:1423 generated SERVER ALERT: Fatal - Insufficient Security
      - :no_suitable_signature_algorithm
     
     16:53:00.635 [info]  TLS :client: In state :hello received SERVER ALERT: Fatal - Insufficient Security
      
     
.

  4) test secure connection open_socket with supplied cacerts (WebSockex.ConnTest)
     test/websockex/conn_test.exs:151
     ** (MatchError) no match of right hand side value: {:error, %WebSockex.ConnError{original: {:tls_alert, {:insufficient_security, 'TLS client: In state hello received SERVER ALERT: Fatal - Insufficient Security\n '}}}}
     stacktrace:
       test/websockex/conn_test.exs:146: WebSockex.ConnTest.__ex_unit_setup_1/1
       test/websockex/conn_test.exs:1: WebSockex.ConnTest.__ex_unit__/2

     The following output was logged:
     
     16:53:00.657 [info]  TLS :server: In state :hello at ssl_handshake.erl:1423 generated SERVER ALERT: Fatal - Insufficient Security
      - :no_suitable_signature_algorithm
     
     16:53:00.664 [info]  TLS :client: In state :hello received SERVER ALERT: Fatal - Insufficient Security
      
     
......

  5) test secure connection close_socket (WebSockex.ConnTest)
     test/websockex/conn_test.exs:170
     ** (MatchError) no match of right hand side value: {:error, %WebSockex.ConnError{original: {:tls_alert, {:insufficient_security, 'TLS client: In state hello received SERVER ALERT: Fatal - Insufficient Security\n '}}}}
     stacktrace:
       test/websockex/conn_test.exs:146: WebSockex.ConnTest.__ex_unit_setup_1/1
       test/websockex/conn_test.exs:1: WebSockex.ConnTest.__ex_unit__/2

     The following output was logged:
     
     16:53:00.681 [info]  TLS :server: In state :hello at ssl_handshake.erl:1423 generated SERVER ALERT: Fatal - Insufficient Security
      - :no_suitable_signature_algorithm
     
     16:53:00.692 [info]  TLS :client: In state :hello received SERVER ALERT: Fatal - Insufficient Security
      
     
..................................................................................

  6) test disconnects and handle_disconnect callback can handle a ssl socket closing during the close loop (WebSockexTest)
     test/websockex_test.exs:1148
     ** (MatchError) no match of right hand side value: {:error, %WebSockex.ConnError{original: {:tls_alert, {:insufficient_security, 'TLS client: In state hello received SERVER ALERT: Fatal - Insufficient Security\n '}}}}
     code: {:ok, pid} = TestClient.start_link(url, %{})
     stacktrace:
       test/websockex_test.exs:1159: (test)

     The following output was logged:
     
     16:53:01.601 [info]  TLS :server: In state :hello at ssl_handshake.erl:1423 generated SERVER ALERT: Fatal - Insufficient Security
      - :no_suitable_signature_algorithm
     
     16:53:01.606 [info]  TLS :client: In state :hello received SERVER ALERT: Fatal - Insufficient Security
      
     
.........

  7) test can connect to secure server (WebSockexTest)
     test/websockex_test.exs:452
     ** (MatchError) no match of right hand side value: {:error, %WebSockex.ConnError{original: {:tls_alert, {:insufficient_security, 'TLS client: In state hello received SERVER ALERT: Fatal - Insufficient Security\n '}}}}
     code: {:ok, pid} = TestClient.start_link(url, %{}, cacerts: WebSockex.TestServer.cacerts())
     stacktrace:
       test/websockex_test.exs:457: (test)

     The following output was logged:
     
     16:53:01.661 [info]  TLS :server: In state :hello at ssl_handshake.erl:1423 generated SERVER ALERT: Fatal - Insufficient Security
      - :no_suitable_signature_algorithm
     
     16:53:01.666 [info]  TLS :client: In state :hello received SERVER ALERT: Fatal - Insufficient Security
      
     
........

  8) test handles a ssl message send right after connecting (WebSockexTest)
     test/websockex_test.exs:479
     ** (MatchError) no match of right hand side value: {:error, %WebSockex.ConnError{original: {:tls_alert, {:insufficient_security, 'TLS client: In state hello received SERVER ALERT: Fatal - Insufficient Security\n '}}}}
     code: {:ok, _pid} = TestClient.start_link(url, %{})
     stacktrace:
       test/websockex_test.exs:484: (test)

     The following output was logged:
     
     16:53:01.697 [info]  TLS :server: In state :hello at ssl_handshake.erl:1423 generated SERVER ALERT: Fatal - Insufficient Security
      - :no_suitable_signature_algorithm
     
     16:53:01.700 [info]  TLS :client: In state :hello received SERVER ALERT: Fatal - Insufficient Security
      
     
.........................................

  9) test can handle initial connect headers (WebSockexTest)
     test/websockex_test.exs:436
     ** (MatchError) no match of right hand side value: {:error, %WebSockex.ConnError{original: {:tls_alert, {:insufficient_security, 'TLS client: In state hello received SERVER ALERT: Fatal - Insufficient Security\n '}}}}
     code: {:ok, pid} = TestClient.start_link(url, %{}, cacerts: WebSockex.TestServer.cacerts())
     stacktrace:
       test/websockex_test.exs:441: (test)

     The following output was logged:
     
     16:53:02.119 [error] Failed to start Ranch listener #Reference<0.4291565793.328990724.49118> in :ranch_tcp:listen([port: 54384]) for reason :eaddrinuse (address already in use)
     
     
     16:53:02.123 [info]  TLS :server: In state :hello at ssl_handshake.erl:1423 generated SERVER ALERT: Fatal - Insufficient Security
      - :no_suitable_signature_algorithm
     
     16:53:02.128 [info]  TLS :client: In state :hello received SERVER ALERT: Fatal - Insufficient Security
      
     
.................................................

Finished in 2.3 seconds
208 tests, 9 failures

Randomized with seed 192878
```

**Comment by Azolo** [comment]
Start with: https://github.com/Azolo/websockex/blob/master/lib/websockex/conn.ex

**Comment by dealloc** [comment]
I also ran some quick tests using Docker to run different Elixir versions.
My code seems to work still when running it in the `elixir:1.7.4-alpine` container, but no longer in the `elixir:1.8.2-alpine` container (there are no containers of versions in between).

Something seems to have broken in 1.8, I'll start looking around (though you'd probably have a better chance spotting it than me, I'm entirely new to the :ssl module and I heard it's terrifyingly complex :p)

**Comment by Azolo** [comment]
> I heard it's terrifyingly complex

It is terribly complex. My suggestion is to look at Erlang OTP release notes.

**Comment by dealloc** [comment]
Weirdly enough, when Discord is _just_ slow enough it comes through, so it's pretty much a race between Discord and the listener.
Still trying to figure out what's going on

**Comment by dealloc** [comment]
I can't seem to find any information about changes in the `:ssl` module between 10.2 - 10.3 though that doesn't mean they're not there.
I'm still grokking the documentation, but I've also learned that SSL really isn't my thing.

How are other libraries not having this problem? Maybe interesting to see how  they differ from this library and hopefully that gives us a clue

**Comment by Azolo** [comment]
> Weirdly enough, when Discord is _just_ slow enough it comes through, so it's pretty much a race between Discord and the listener.
> Still trying to figure out what's going on

It may be an issue with the transfer of the socket owner to a new socket. It shouldn't be, but could be.



> How are other libraries not having this problem? Maybe interesting to see how they differ from this library and hopefully that gives us a clue

I don't know, but I would like to transfer to using [mint][0]. There wasn't a low level enough http library before.

[0]: https://github.com/elixir-mint/mint

**Comment by dealloc** [comment]
Is the HTTP connection kept open after the request is dispatched?

**Comment by haljin** [comment]
Is there anybody still looking at that? I am having the same problem, which is proving to be very difficult to reproduce as it requires running a certain load on the system. In short, this problem only occurs if I redeploy one of our services in K8s which causes about 150 websockets to die and immediately restart and attempt to reconnect. If I redeploy "slower" taking pods one by one, only about 50 connections go down at a time and no problems occur.

I have fixed tests in this library by simply updating the certificate to something I had lying around - the problem is that yours are using md5 as a signature algorithm and Erlang's SSL definitely does not think that's a good idea. Unfortunately, the tests all pass, so I am still unable to reproduce in any other way than the long-winded K8s deployment.

**Comment by dealloc** [comment]
I have since moved to using Gun for my own project.
You can see my implementation [here](https://github.com/dealloc/wumpex/blob/master/lib/wumpex/base/websocket.ex).

**Comment by Azolo** [comment]
@haljin Thanks for the information on the certificate on the tests.

This is a really hard one to pin down and I don't have a lot of time to work on this library anymore. 😞 

This is at the top of the list of things I want to do when I get time.

**Comment by haljin** [comment]
Well, I guess then you will be glad to hear that I seem to have fixed it. :) I'll cook up a PR tomorrow that fixed that + loads some new certs in that should also fix tests - if you could push that to Hex that is? I'd rather use a Hex version than my fork.

**Comment by haljin** [comment]
Ooh I should've read through the issues more carefully. #74 mentions the exact thing that I have fixed. Would've saved me a couple of days trying to figure out where the message goes and which part of the application (client or server) is actually at fault 😅
