### ISSUE TITLE
Please release 0.4.3 with continuation support

### ISSUE THREAD

**Issue by mspanc** [Azolo/websockex#88]
Hello,

can I ask you to release 0.4.3 which contains this fix?

https://github.com/Azolo/websockex/commit/6f40893ce60933fbdda48982baa4f540417e2400

The library quickly becomes useless without continuation support.

Thank you.

**Comment by rupurt** [comment]
Big +1 to this. Ideally I'd prefer not to create a fork package with these fixes.

**Comment by rupurt** [comment]
Big +1 to this @Azolo. Ideally I'd prefer not to create a fork package with these fixes.

**Comment by Azolo** [comment]
I'm super sorry.

Give me 24 hours.

**Comment by Azolo** [comment]
Alright, I'm so sorry it took so long.

[Version 0.4.3 has been released](https://hex.pm/packages/websockex/0.4.3)

**Comment by rupurt** [comment]
No worries. Thank you @Azolo :partying_face:
