### ISSUE TITLE
Telemetry Events?

### ISSUE THREAD

**Issue by pedro-gutierrez** [Azolo/websockex#99]
Hello,

This is a question or a feature request.

I was wondering whether it would be a good idea to add [telemetry](https://github.com/beam-telemetry/telemetry) to this library?

Initially something simple such as:

* Connections
* Disconnections
* Frames sent/received

Happy to try to submit a PR if such a feature would be welcome.

Thank you! :)

**Comment by Azolo** [comment]
Yeah, that would be cool.

I think the hardest part would be testing telemetry events.

**Comment by pedro-gutierrez** [comment]
Hey thank you. I gave it a try, and it seems to be working okay, but unfortunately the `:telemetry` application only works with OTP 21 and later, so the CI is failing for older releases.
